import { createRequire } from 'node:module'

const resolvePackage = createRequire(import.meta.url).resolve

export default defineNuxtConfig({
  compatibilityDate: '2026-07-26',

  modules: ['@nuxt/eslint', 'nuxt-auth-utils'],

  devtools: {
    enabled: true,
  },

  css: [
    '@fontsource/raleway/latin-400.css',
    '@fontsource/raleway/latin-600.css',
    '@fontsource/raleway/latin-700.css',
    '@fontsource/raleway/latin-800.css',
    '~/assets/css/main.css',
  ],

  app: {
    head: {
      htmlAttrs: {
        lang: 'fr',
      },
      charset: 'utf-8',
      viewport: 'width=device-width, initial-scale=1, viewport-fit=cover',
      link: [
        { rel: 'icon', type: 'image/png', href: '/favicon.png' },
        { rel: 'manifest', href: '/site.webmanifest' },
      ],
      meta: [
        { name: 'theme-color', content: '#0b1238' },
        { name: 'color-scheme', content: 'dark' },
      ],
    },
  },

  runtimeConfig: {
    // Private CMS configuration. Values are injected with NUXT_* variables.
    cmsDataDir: '.data',
    cmsSuperAdminDiscordId: '',
    // Read-only aggregate generated by BigBadBot, never its raw database.
    participationDataPath: '.data/stats/participations.sqlite',
    // Private, authenticated HTTP bridge to BigBadBot. The production secret
    // is read from a Docker secret file and is never exposed to the browser.
    bigbadbotBridgeUrl: '',
    bigbadbotBridgeSecret: '',
    bigbadbotBridgeSecretFile: '',
    bigbadbotBridgeRequired: false,
    session: {
      maxAge: 60 * 60 * 8,
    },
    public: {
      siteUrl: 'http://localhost:3000',
      matomoUrl: '',
      matomoSiteId: '',
    },
  },

  routeRules: {
    '/**': {
      headers: {
        'X-Content-Type-Options': 'nosniff',
        'Referrer-Policy': 'strict-origin-when-cross-origin',
        'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
      },
    },
    '/admin/**': {
      headers: {
        'Cache-Control': 'private, no-store',
        'Content-Security-Policy': "frame-ancestors 'none'",
        'X-Frame-Options': 'DENY',
        'X-Robots-Tag': 'noindex, nofollow, noarchive',
      },
    },
    '/auth/**': {
      headers: {
        'Cache-Control': 'private, no-store',
        'Content-Security-Policy': "frame-ancestors 'none'",
        'X-Frame-Options': 'DENY',
        'X-Robots-Tag': 'noindex, nofollow, noarchive',
      },
    },
    '/api/admin/**': {
      headers: {
        'Cache-Control': 'private, no-store',
        'Content-Security-Policy': "frame-ancestors 'none'",
        'X-Frame-Options': 'DENY',
      },
    },
    '/mes-participations': {
      headers: {
        'Cache-Control': 'private, no-store',
        'Content-Security-Policy': "frame-ancestors 'none'",
        'X-Frame-Options': 'DENY',
        'X-Robots-Tag': 'noindex, nofollow, noarchive',
      },
    },
    '/inscriptions': {
      headers: {
        'Cache-Control': 'private, no-store',
        'Content-Security-Policy': "frame-ancestors 'none'",
        'X-Frame-Options': 'DENY',
        'X-Robots-Tag': 'noindex, nofollow, noarchive',
      },
    },
    '/creneaux': {
      headers: {
        'Cache-Control': 'private, no-store',
        'Content-Security-Policy': "frame-ancestors 'none'",
        'X-Frame-Options': 'DENY',
        'X-Robots-Tag': 'noindex, nofollow, noarchive',
      },
    },
    '/creneaux/**': {
      headers: {
        'Cache-Control': 'private, no-store',
        'Content-Security-Policy': "frame-ancestors 'none'",
        'X-Frame-Options': 'DENY',
        'X-Robots-Tag': 'noindex, nofollow, noarchive',
      },
    },
    '/api/member/**': {
      headers: {
        'Cache-Control': 'private, no-store',
        'Content-Security-Policy': "frame-ancestors 'none'",
        'X-Frame-Options': 'DENY',
        'X-Robots-Tag': 'noindex, nofollow, noarchive',
      },
    },
  },

  nitro: {
    // CMS pages stay dynamic so a publication is visible without rebuilding.
    prerender: {
      crawlLinks: false,
      routes: [],
    },
    // Nitro 2.13 uses traceInclude for native Node dependencies.
    externals: {
      traceInclude: [resolvePackage('better-sqlite3'), resolvePackage('sharp')],
    },
  },

  typescript: {
    strict: true,
    typeCheck: true,
  },
})
